repo_url,commit_hash,error
pyannote/segmentation,30794f422626833bbaad102efa819874d43c48ef,"Cmd('git') failed due to: exit code(128)
  cmdline: git clone -v -- git@hf.co:pyannote/segmentation tmp\pyannote+segmentation
  stderr: 'Cloning into 'tmp\pyannote+segmentation'...
remote: 
remote: ========================================================================
remote: 
remote: ERROR: Access denied: repository is gated and you are not in the authorized list.

remote: 
remote: ========================================================================
remote: 
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
'"
